### ISSUE TITLE
Add Station Images

### ISSUE THREAD

**Issue by nickfong** [nickfong/CS160-Collaboration#27]
Find CC-licensed and relevant images ~~to~~ of points of interest around stations and add them to the `drawable` directory. 

Then update the chain of `if (destinationSelected ==...` statements in `postSelection.java` (and probably change to a switch statement for easier readability).  

Assigning `priority` since we should have more images before the demo

**Comment by michaelyxu** [comment]
Make sure all images are .png otherwise android won't display it

I can have this completed before we turn in our final product, prob can't
by demo time

On Wednesday, December 9, 2015, Nick Fong <notifications@github.com> wrote:

> Find CC-licensed and relevant images to points of interest around stations
> and add them to the drawable directory.
>
> Then update the chain of if (destinationSelected ==... statements in
> postSelection.java (and probably change to a switch statement for easier
> readability).
>
> Assigning as priority since we should have more images before the demo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nickfong/CS160-Collaboration/issues/27>.
>


-- 
University of California, Berkeley | 2016
B.S. Electrical Engineering & Computer Science
Industrial Engineering & Operations Research Minor
(909) 895 9012 | michaelxuu@berkeley.edu
michaelxu.com

**Comment by nickfong** [comment]
Station images were added in 3c3b6b2.  Closing.
